import { withSSRGuest } from "@/HOC/withSSRGuest";
import { useAuth } from "@/hooks/useAuth";
import styles from "@/styles/Home.module.css";
import Head from "next/head";
import { FormEvent, useState } from "react";

export default function Home() {
  const { signIn } = useAuth();

  const [email, setEmail] = useState("filipe@dias.com");
  const [password, setPassword] = useState("123456");

  async function handleSubmit(event: FormEvent) {
    event.preventDefault();
    const data = {
      email,
      password,
    };

    await signIn(data);
  }

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form className={styles.container} onSubmit={handleSubmit}>
        <input
          type="email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
        />
        <input
          type="password"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
        />
        <button type="submit">Entrar</button>
      </form>
    </>
  );
}

export const getServerSideProps = withSSRGuest(async (ctx) => {
  return {
    props: {},
  };
});
